version: '3.8'

services:
  # API Gateway
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ROUTE_ENGINE_URL=http://route-engine:8001

  # Route Engine
  route-engine:
    build: ./services/route-engine
    ports:
      - "8001:8001"
    environment:
      - PORT=8001

networks:
  default:
    name: logichain-network
